env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=1
    binary: reverse_sjis_go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
        post:
          upx
            dist/reverse_sjis_go_linux_amd64/reverse_sjis_go
            dist/reverse_sjis_go_windows_amd64/reverse_sjis_go.exe
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
